### ISSUE TITLE
Cluttered views folder

### ISSUE THREAD

**Issue by clinei** [rejectedsoftware/vibelog#9]
The name format of the Diet templates inside the `views` folder is too long and the amount of unrelated files in a single folder adds to the confusion.
I suggest using separate folders i.e. 
`views/vibelog/admin/editpostlist.dt` 
instead of 
`views/vibelog.admin.editpostlist.dt`.
That way the files in a folder are related to only one component and a single layout file can exist on every level of a nested hierarchy e.g. `views/vibelog/layout.dt` and `views/vibelog/admin/layout.dt`.

An example of this method can be seen at https://github.com/clinei/decom/tree/master/views

**Comment by s-ludwig** [comment]
Unfortunately doesn't work on Windows.

**Comment by clinei** [comment]
The pathing or the example?

**Comment by s-ludwig** [comment]
DMD on Windows disallows string imports in subdirectories for rather obscure security reasons, so there is no way around using these prefixes.

**Comment by clinei** [comment]
Damn.

**Comment by clinei** [comment]
Wait, you could still add custom -J paths.

**Comment by s-ludwig** [comment]
Yes, you could use separate paths, but you'd still need the prefixes to avoid name clashes. But IMO the number of files in the folder isn't so much of an issue, as long as they are properly sorted. The prefix is also important anyway to avoid name clashes between different packages that are compiled together (e.g. vibelog + vibenews).

**Comment by clinei** [comment]
True.
That bug really needs to be fixed.

**Comment by s-ludwig** [comment]
Yeah, the security considerations really don't make much sense. The rationale is that a malicious string import could somehow break out of the registered string import directories. But a) there usually are many other ways to read arbitrary files during build time, let alone during run time, and b) It would be easy to restrict the path to a subset of possible notations, so that it can be guaranteed to not leave the directory (except for symlinks).
